server:
  port: 8084
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: mqTestDefault
          group: secondGroup
          content-type: application/json
            